<div class="clearfix" id="view_user">
    <div class="sub_column_right right round" id="user_general" style="width: 100%">
        <div class="padding_wrapper">
            <div class="two_column_item medium">
   
                 <div class="item clearfix">
                    <div class="left">
                        <?php echo $this->translate->_('Disclaimer Text:'); ?>
                    </div> <!-- end left -->
                    <div class="right">
                        <span style="white-space:pre-wrap"><?php echo $this->setupInfo->disclaimer_text; ?></span>
                    </div> <!-- end right -->
                </div> <!-- end clearfix -->

            </div> <!-- end two_column_item -->
        </div> <!-- end padding_wrapper -->

    </div> <!-- end sub_column_right -->
                                                                                                             
    <div class="spacer clear"><!-- --></div>
                                                                

</div> <!-- end content -->

