<div class="padding_wrapper">
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <h5><?php echo $this->translate->_('It seems that you don\'t have enough privileges to see this page.<br />If you feel there is something wrong with this application, you may get some help by emailing <a href="http://amediacreative.com" title="Visit Amedia Creative">Amedia Creative</a> at <a href="wecare@amediacreative.com" title="Email Amedia Creative">wecare@amediacreative.com</a>.<br />Thank you.'); ?></h5>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
</div> <!-- end padding_wrapper -->
<div class="clear"><!-- --></div>