<?php
	$this->form->setAction($this->serverUrl($this->url()));
	$errorMessages = $this->form->getMessages();
?>
						<div class="content_section clearfix round" id="add_user">
                        	
                            <form id="<?php echo $this->form->getName(); ?>" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">

                                <div class="global_input_wrapper" id="user_form_fields">
                                
                                	<input type="hidden" name="ID_user" value="<?php echo $this->form->getElement('ID_user')->getValue(); ?>" />
                                
                                	<h4><?php echo $this->translate->_('Required Information'); ?></h4>

                                    <div class="left val_label">
                                        <label for="user_password" class="titletag"><?php echo $this->translate->_('New Password'); ?></label>
                                    </div> <!-- end left -->
                                    
                                    <div class="right val_label">
                                        <label for="password_conf" class="titletag"><?php echo $this->translate->_('Confirm New Password'); ?></label>
                                    </div> <!-- end right -->
  
                                    <div class="left val_class_holder">
                                        <div class="input">
                                            <span class="left"><!-- --></span>
                                            <span class="mid">
                                                <input value="<?php echo $this->form->getElement('user_password')->getValue(); ?>" id="<?php echo $this->form->getElement('user_password')->getName(); ?>" class="" name="<?php echo $this->form->getElement('user_password')->getName(); ?>" type="password" />
                                            </span>
                                            <span class="right"><!-- --></span>
                                        </div> <!-- end input -->
                                        <p class="error spacer clear"<?php echo isset($errorMessages['user_password']) ? ' style="text-indent: 0px;"' : ''; ?>>
                                        <?php if (isset($errorMessages['user_password'])): ?>
                                        	<?php foreach($errorMessages['user_password'] as $error): ?>
                                        	<?php echo $error; ?><br />
                                        	<?php endforeach; ?>
                                        <?php else: ?>
                                        	<?php echo $this->translate->_('Please enter a password.'); ?>
                                        <?php endif; ?>
                                        </p>
                                    </div> <!-- end val_class_holder -->
                                    
                                    <div class="right val_class_holder">
                                        <div class="input">
                                            <span class="left"><!-- --></span>
                                            <span class="mid">
                                                <input value="<?php echo $this->form->getElement('password_conf')->getValue(); ?>" id="<?php echo $this->form->getElement('password_conf')->getName(); ?>" class="" name="<?php echo $this->form->getElement('password_conf')->getName(); ?>" type="password" />
                                            </span>
                                            <span class="right"><!-- --></span>
                                        </div> <!-- end input -->
                                        <p class="error spacer clear"<?php echo isset($errorMessages['password_conf']) ? ' style="text-indent: 0px;"' : ''; ?>>
                                        <?php if (isset($errorMessages['password_conf'])): ?>
                                        	<?php foreach($errorMessages['password_conf'] as $error): ?>
                                        	<?php echo $error; ?><br />
                                        	<?php endforeach; ?>
                                        <?php else: ?>
                                        	<?php echo $this->translate->_('Please enter a password that matches the New Password field.'); ?>
                                        <?php endif; ?>
                                        </p>
                                    </div> <!-- end val_class_holder -->
                                    
                                    <div class="clear"><!-- --></div>
                                    
                                    <div class="hr"><hr /></div>
                                    
                                    <div class="btm-runner clearfix">
                                    	<ul>
                                        	<li class="button no_right_margin"><input type="submit" class="submit" value="<?php echo $this->translate->_('submit'); ?>" id="submit_user_add" tabindex="13" /></li>
                                    		<li class="link"><a title="<?php echo $this->translate->_('Go Back'); ?>" class="inline-link" href="javascript: history.go(-1);"><?php echo $this->translate->_('Go Back'); ?></a></li>
                                        </ul>
                                    </div> <!-- end btm-runner -->

                                </div> <!-- end global_input_wrapper -->
                            </form> <!-- end add_user_form -->

                        </div>
                        
