<?php
$locales['en_US'] = 'English';
$locales['zh_CN'] = 'Chinese';
    $formData = $this->form->getValues();
?>

<?php if ($this->formErrorMessages != ""): ?>
<p style="font-weight: bold; color: red;"><?php $this->formErrorMessages; ?></p>
<?php endif; ?>

<section class = "main lft grid24" >

<article>
    <header>
        <h2><?php echo $this->translate->_('Edit My Info'); ?></h2>
        <br><br>
    </header>

    <div class="user_options grid7 lft">
        <p class = "p_c">
            <?php  if(!isset($formData['user_avatar_file'])) { $formData['user_avatar_file'] =  0;} ?>
            <a class="btn_default iBlk buttonfix lightbox fancybox.ajax"  href="<?php echo $this->serverUrl('/people/user/get-addr-avatar/id_avatar/'. $this->avatarFile); ?>" ><?php echo $this->translate->_('Change Avatar'); ?></a>
        </p>
        
        <div class="user_avatar fixavatar">
            <img class="avatar_file" src="<?php echo  $this->avatarInfo ;?>" alt="" style="width: 130px;height: 130px;" />
        </div>
    </div><!-- user_options end -->
                        
                        
    <form id="user_form" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>" class="grid26 rgt">
        <input id="ID_company_1" type="radio" value="<?php echo $this->userCompany['ID_company']; ?>" name="ID_company" checked="checked" style="display: none;">
        
        <input type="hidden" name="user_level" id="user_level" value="<?php echo Zend_Auth::getInstance()->getIdentity()->user_level;  ?>" />
        <input type="hidden" name="ID_auth" id="ID_auth" value="<?php echo $formData['ID_auth']; ?>" />        
        <input type="hidden" name="ID_user" id="ID_user" value="<?php echo $formData['ID_user']; ?>" />
        <input type="hidden" name="ID_optional" id="ID_optional" value="<?php echo $formData['ID_optional']; ?>" />       
        <input type="hidden" name="user_avatar_file" id="user_avatar_file" value="<?php echo $this->avatarFile; ?>" />

        <div class="grid17 blk lft">
            <label for="user_email"><?php echo $this->translate->_('Email'); ?> *</label>
            <input type="text" id="user_email" name="user_email" value="<?php echo $formData['user_email']; ?>" />
        
            <p class="error spacer clear"<?php echo isset($errorMessages['user_email']) ? ' style="text-indent: 0px;"' : ''; ?>>
            <?php if (isset($errorMessages['user_email'])): ?>
                <?php foreach($errorMessages['user_email'] as $error): ?>
                <?php echo '<font color = "red">'.$error.'</font>'; ?><br />
                <?php endforeach; ?>
            <?php endif; ?>
            </p>
        </div>

        <div class="grid17 blk rgt">
            &nbsp;
        </div>  
        
        <div class="clearfix"><!--&nbsp--></div>

        <div class="grid17 blk lft">
            <label for="user_firstname"><?php echo $this->translate->_('First Name'); ?></label>
            <input type="text" id="user_firstname" name="user_firstname" value="<?php echo $formData['user_firstname']; ?>" />
        </div>

        <div class="grid17 blk rgt">
            <label for="user_surname"><?php echo $this->translate->_('Last Name'); ?></label>
            <input type="text" id="user_surname" name="user_surname" value="<?php echo $formData['user_surname']; ?>" />
        </div>
        
        <div class="clearfix"><!--&nbsp--></div>

        <div class="grid17 blk lft">
            <label for="user_password"><?php echo $this->translate->_('Password'); ?></label>
            <input type="password" id="user_password" name="user_password" />
        </div>
        
        <div class="grid17 blk rgt">
            <label for="password_conf"><?php echo $this->translate->_('Re-type Password'); ?></label>
            <input type="password" id="password_conf" name="password_conf"/>
        </div>
        
        <div class="clearfix"><!--&nbsp--></div>
                                                                
        <div class="grid17 blk lft">
            <label for="user_phone"><?php echo $this->translate->_('Phone'); ?></label>
            <input type="text" id="user_phone" name = "user_phone" value="<?php echo $formData['user_phone']; ?>" />
        </div>
        
        <div class="grid17 blk rgt">
            <label for="user_mobile"><?php echo $this->translate->_('Mobile'); ?></label>
            <input type="text" id="user_mobile" name= "user_mobile" value="<?php echo $formData['user_mobile']; ?>" />
        </div>
                            
        <div class="clearfix"><!--&nbsp--></div>
        
        <div class="grid17 blk lft">
            <label for="user_locale"><?php echo $this->translate->_('Language'); ?></label>
            <?php echo $this->formSelect('user_locale', $formData['user_locale'], array('id' => 'user_locale', 'class'=>''), $this->languageOptions)."\n";?>
        </div>
        
        <div class="grid17 blk rgt">
            <label for="user_timezone"><?php echo $this->translate->_('Time Zone'); ?></label>
            <select name="user_timezone" id="user_timezone" show="1">
                <option value=""><?php echo $this->translate->_('Please Select...'); ?></option>
                    <?php foreach(DateTimeZone::listIdentifiers() as $tz): ?>
                        <option 
                            value="<?php echo $tz; ?>" 
                            <?php echo $formData['user_timezone'] == $tz ? ' selected="selected"' : ''; ?>
                        >
                            <?php echo ucwords(str_replace(array('/', '_'), array(' - ', ' '), $tz)); ?>
                        </option>
                    <?php endforeach; ?>
            </select>
        </div>
        
        <div class="clearfix"><!--&nbsp--></div>
                            
        <div class="bottom">
            <button type="submit" class="green rgt"><?php echo $this->translate->_('Save'); ?></button>
                                            
            <button class="red goback_btn rgt" style="margin-right:10px;" onclick = "history.go(-1);"  ><?php echo $this->translate->_('Go Back'); ?></button>

            
            <div class="clearfix"><!--&nbsp--></div>
        </div>
    </form>
    
    <div class="clearfix"><!--&nbsp--></div>
</article>

</section>