<?php
	$fileUrl = '';
	if ($this->fileUploaded == true)
		$fileUrl = $this->serverUrl('/uploads/' . $this->fileFullName);
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <title>Uploader</title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="shortcut icon" href="<?php echo $this->serverUrl('favicon.ico'); ?>" />
  <!-- jQuery -->
    <script type="text/javascript" src="<?php echo $this->serverUrl('/assets/js/application/jquery-1.7.2.min.js'); ?>"></script>
	<!-- MOBILE -->
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no" />

    <!-- Stylesheet -->
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->serverUrl('/assets/css/style/reset.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->serverUrl('/assets/css/style/compiled.styles.css'); ?>" />

	<script type="text/javascript">
	//<![CDATA[


		$(document).ready(function() {
	  		/*-------------- FILE --------------*/
		    $('.iFile').each(function(){
		        var r = $(this).find('input:file').attr('rel');
		        $(this).append(r);
		    }).change(function(){
		    	$(this).prev('.iFileDescription').html('<i class="progress_bar_blue animate_bar">Loading...</i>');
		    	$('#FormFileUpload').submit();
		    });

		    $('.iFileDescription .remove_btn').click(function(){
		    	
		    	<?php if ($this->jsResetCallback != ''): ?>
					window.top.window.<?php echo $this->jsResetCallback; ?>('<?php echo $this->fileId; ?>', '<?php echo $fileUrl; ?>', '<?php echo $this->jsParameterCallback; ?>');
				<?php endif; ?>
				
				$('.iFile file').val('');
				$(this).attr('style', 'display:none');
				$('#file_name').html('');

				return false;
			});
		} );

    //]]>
	</script>

	<?php if ($this->fileUploaded == true): ?>
		<script type="text/javascript">
		//<![CDATA[

		  	$(document).ready(function() {
				// JS Callback function
				// First parameter is File Id, Second is File full path

				<?php if ($this->jsResetCallback != ''): ?>
					window.top.window.<?php echo $this->jsCallback; ?>('<?php echo $this->fileId; ?>', '<?php echo $fileUrl; ?>', '<?php echo $this->jsParameterCallback; ?>');
				<?php endif; ?>
				
		    } );

		//]]>
		</script>
	<?php endif; ?>

	<style type="text/css">

		body {
			background: #ffffff;
		}

	</style>

</head>
<body>
	<?php echo $this->layout()->content; ?>
</body>
</html>